# Generated by Django 5.2 on 2025-07-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commonnutrition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='recodanmation/Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('subtype', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nutritionrequirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('nutrient_type', models.CharField(max_length=500)),
                ('s_range', models.CharField(max_length=100)),
                ('e_range', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomandation.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Testlabvalues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_value', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('diseases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomandation.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomandation.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomandation.user')),
            ],
        ),
    ]
