# Generated by Django 5.2.7 on 2025-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomandation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonnutrition',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
