# Generated by Django 5.2.7 on 2025-11-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomandation', '0002_alter_commonnutrition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
