# Generated by Django 5.2.7 on 2025-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomandation', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Admin', max_length=500),
        ),
    ]
