# Generated by Django 5.2.7 on 2025-11-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomandation', '0004_admin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
    ]
